# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z045ffg900-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /users/tareelou/neural_network_sfixed/neural_network_sfixed.cache/wt [current_project]
set_property parent.project_path /users/tareelou/neural_network_sfixed/neural_network_sfixed.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:zc706:part0:1.3 [current_project]
set_property ip_output_repo /users/tareelou/neural_network_sfixed/neural_network_sfixed.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library neuronal {
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/MATH_REAL.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_float_types_c.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/fixed_pkg_c.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/ieee/float_pkg_c.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/package_type.vhd
}
read_vhdl -library xil_defaultlib {
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/neuro_bio.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/tree_reduction.vhd
  /users/tareelou/neural_network_sfixed/neural_network_sfixed.srcs/sources_1/imports/Neural_HDL_V_SFIXED/top_level.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top top_level -part xc7z045ffg900-2


write_checkpoint -force -noxdef top_level.dcp

catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
